### PR TITLE
add option for resolving links

### PR DESCRIPTION
**Pull request by melono6**
Was having an issue where i was using richTextOutputFormat: 'none'
The assets being linked in the richtext eg: an image was not pulling in the data as resolveLinks is hardcoded to false.

added an option to set to true

### CODE REVIEW

**Comment by smnh** [comment]
Hey @melono6,
Just curious, how do you access images from within the rich text field?

**Comment by melono6** [comment]
you enable the option in rich text settings on the right
Screenshot 2021-04-06 at 09 40 39

and then you can add in top right in the richtext
Screenshot 2021-04-06 at 09 40 59

**Review by smnh — APPROVED** [review]

**Comment by smnh** [comment]
Hey @melono6 

Thanks for the PR, approved.

P.S.: in my previous question I meant how do you access images embedded in rich text from within your website code.

Also note, that with this flag, Contentful will resolved links between the objects.
But this Sourcebit plugin has its own method of resolving objects by using `value.sys.id` of one field to match `id` of another object:
https://github.com/stackbit/sourcebit-source-contentful/blob/23e13cbf4b/lib/contentful-util.js#L71-L84

I hope these two methods of resolving links won't conflict.

**Comment by melono6** [comment]
i am using the contentful rich text package
https://www.npmjs.com/package/@contentful/rich-text-react-renderer

you then pass the array that contentful gives you into the function and can provide differnet rendering for different node block types:
eg:
`{documentToReactComponents(richText, {
          renderNode: {
            [INLINES.HYPERLINK]: (node, renderedValues) => {
              return (
                <Link href={node.data.uri} passHref>
                  <a target="_blank" rel="noopener">
                    {renderedValues}
                  </a>
                </Link>
              );
            },
            [BLOCKS.EMBEDDED_ASSET]: (node) => {
              return (
                <div>
                  <Image
                    src={node.data.target.fields.file['en-US'].url}
                    alt={node.data.target.fields.file['en-US'].fileName}
                    width={node.data.target.fields.file['en-US'].details.image.width}
                    height={node.data.target.fields.file['en-US'].details.image.height}
                  />
                </div>
              );
            },
            [INLINES.ENTRY_HYPERLINK]: (node, text) => {
              const { slug } = node.data.target.fields;
              return (
                <Link href={`/${slug}`} passHref>
                  <a>{text}</a>
                </Link>
              );
            },
            [INLINES.ASSET_HYPERLINK]: (node) => {
              const { title, file } = node.data.target.fields;
              const { url } = file;
              return (
                <Link href={url} passHref>
                  <a target="_blank" rel="noopener">
                    {title}
                  </a>
                </Link>
              );
            },
          },
        })}`

the image node being BLOCKS.EMBEDDED_ASSET in above snippet

**Comment by smnh** [comment]
Published under `v0.6.5`

**Pull request merged**
